# -*- coding: utf-8 -*-
"""api_file_search_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bi50t2tT3jNz3nB3JaXUgHqc0csPhL70
"""

from openai import OpenAI
from config import OPENAI_API_KEY

client = OpenAI(api_key=OPENAI_API_KEY)

# Vector Store 생성

vector_store = client.vector_stores.create(
    name="SafeMate_KISA_Guide"
)

print(vector_store.id)

# PDF 업로드

file = client.files.create(
    file=open("KISA_Phishing_Guide.pdf","rb"),
    purpose="assistants"
)

print(file.id)

# Vector Store 등록

vector_file = client.vector_stores.files.create(
    vector_store_id=vector_store.id,
    file_id=file.id
)

print(vector_file)

"""#### [검색 품질 테스트]"""

# 검색 테스트1

query = "의심스러운 URL을 클릭했어요."

result = client.vector_stores.search(
    vector_store_id=vector_store.id,
    query=query
)

print("=" * 80)
print("📌 File Search 기술검증 결과")
print("=" * 80)

print(f"사용자 질문 : {query}")
print()

for i, data in enumerate(result.data, start=1):
    print(f"[관련 문서 {i}] (관련도 순위 {i})")
    print(f"파일명        : {data.filename}")
    print(f"유사도 점수   : {data.score:.3f}")
    print("-" * 80)

    for content in data.content:
        print(content.text)

    print("\n")

# 검색 테스트2

query = "스푸핑 메일이 무엇인가요?"

result = client.vector_stores.search(
    vector_store_id=vector_store.id,
    query=query
)

print("=" * 80)
print("📌 File Search 기술검증 결과")
print("=" * 80)

print(f"사용자 질문 : {query}")
print()

for i, data in enumerate(result.data, start=1):
    print(f"[관련 문서 {i}] (관련도 순위 {i})")
    print(f"파일명        : {data.filename}")
    print(f"유사도 점수   : {data.score:.3f}")
    print("-" * 80)

    for content in data.content:
        print(content.text)

    print("\n")

# 검색 테스트3

query = "기관을 사칭한 이메일이 왔어요."

result = client.vector_stores.search(
    vector_store_id=vector_store.id,
    query=query
)

print("=" * 80)
print("📌 File Search 기술검증 결과")
print("=" * 80)

print(f"사용자 질문 : {query}")
print()

for i, data in enumerate(result.data, start=1):
    print(f"[관련 문서 {i}] (관련도 순위 {i})")
    print(f"파일명        : {data.filename}")
    print(f"유사도 점수   : {data.score:.3f}")
    print("-" * 80)

    for content in data.content:
        print(content.text)

    print("\n")

# 검색 테스트4

query = "스미싱 문자 신고는 어디서 하나요?"

result = client.vector_stores.search(
    vector_store_id=vector_store.id,
    query=query
)

print("=" * 80)
print("📌 File Search 기술검증 결과")
print("=" * 80)

print(f"사용자 질문 : {query}")
print()

for i, data in enumerate(result.data, start=1):
    print(f"[관련 문서 {i}] (관련도 순위 {i})")
    print(f"파일명        : {data.filename}")
    print(f"유사도 점수   : {data.score:.3f}")
    print("-" * 80)

    for content in data.content:
        print(content.text)

    print("\n")